### ISSUE TITLE
Exibir Copia e Cola

### ISSUE THREAD

**Issue by ramondiver22** [Open-Pix/openpix-developers#765]
Olá, possuo um script que após inserir o valor de pagamento ele retorna somente o Qrcode, gostaria que fosse exibido o código Copia e Cola abaixo. 

![Screenshot_20231221-164625](https://github.com/Open-Pix/openpix-developers/assets/147664756/79111ac8-793d-44ae-ba70-f6e54fa87704)
![Screenshot_20231221-162652](https://github.com/Open-Pix/openpix-developers/assets/147664756/dc05890a-f32a-4e37-8cde-a58457fe9dbf)

Repositório do script: [https://github.com/MortalSoft/CASINO-SITE](url)

Pix.php [https://github.com/MortalSoft/CASINO-SITE/blob/main/core/pages/pix.php](url)

OpenPix.class.php [https://github.com/MortalSoft/CASINO-SITE/blob/main/core/classes/OpenPIX.class.php](url)

**Comment by daniloab** [comment]
Ola, o repositorio em questão é customizado e não pertence a OpenPix. No caso, construiram uma solução em cima da nossa api.

Para você realizar a mudança necessária teria que editar direto no seu repositório.

A api devolve o campo `brCode` basta expor ele para copiar e colar
