### ISSUE TITLE
Curl exibido na página "Pagando um Pix QRCode de teste" Parece não funcionar

### ISSUE THREAD

**Issue by zeyuri** [Open-Pix/openpix-developers#782]
Estava testando minha integração e quando fui usar o curl exibido [nessa página](https://developers.openpix.com.br/docs/test/test-pay-pix-qrcode) para marcar uma cobrança como paga, e obtive a seguinte resposta:

Redirecting to <a href="https://openpix.com.br/">https://openpix.com.br/</a>.

Será q eu fiz alguma coisa de errada ou esse endpoint não funciona mais?

Eu acabei usando a funcionalidade na interface na tela de cobrança no app.

**Comment by sibelius** [comment]
acredito que faltou passar o appID no header

![image](https://github.com/Open-Pix/openpix-developers/assets/2005841/90dcb13c-b54c-4298-959e-3eb064fb933a)

**Comment by zeyuri** [comment]
Eu tentei o curl abaixo e não funcionou:

```bash
curl 'https://api.openpix.com.br/api/v1/testing?identifier=7f323483681f4943a1f68b19f41283b9' -H 'Authorization: Q2xpZW50X0lkX2RkM......'
```

**Comment by sibelius** [comment]
pagar uma cobrança pix ou um qrcode estatico ?

ele faz um redirect mesmo quando dá certo

**Comment by zeyuri** [comment]
Hmmm, talvez seja isso, eu criei a cobrança usando o endpoint de cobrança, peguei o identificador e tentei. Só funciona pra QRCode estático?

Se sim ta explicado, de toda forma seria massa retornar talvez um erro na api ao tentar usar com o Id de uma cobrança? Talvez eliminasse possíveis confusões da parte de quem viu a documentação

**Comment by sibelius** [comment]
temos ambos

pagar qrcode estatico e pagar cobrança

https://developers.openpix.com.br/docs/test/test-pay-pix
https://developers.openpix.com.br/docs/test/test-pay-pix-qrcode

**Comment by zeyuri** [comment]
Ahhh saquei, de fato o primeiro link funciona perfeitamente pra cobranças. Testei aqui. Valeu!
